### ISSUE TITLE
Call to undefined method MediaWiki\Shell\CommandFactory::createBoxed()

### ISSUE THREAD

**Issue by WolfgangFahl** [samwilson/diagrams-extension#75]
```
Diagrams | 0.9.4 (b52eef6) 00:46, 18 December 2022
```
This is using a dockerized MW 1.35.9 with a clean fresh install - its a showstopper

49c978d9393ff7209a3a6920] /index.php?title=Template:Link&action=submit Error from line 134 of /var/www/html/extensions/Diagrams/includes/Diagrams.php: Call to undefined method MediaWiki\Shell\CommandFactory::createBoxed()

**Comment by costerutilo** [comment]
I have the same problem. Is there a solution to this?

**Comment by WolfgangFahl** [comment]
The problem doesn't seem to manifest itself in my https://github.com/BITPlan/ProfiWiki based installations. I do not know why.

**Comment by kghbln** [comment]
I got this too, for MediaWiki 1.35.14 and Diagrams 1.13.1

### Issue
```
[cfbc5c713117609962fe427f] /wiki/GraphViz Error from line 159 of /../w/extensions/Diagrams/includes/Diagrams.php: Call to undefined method MediaWiki\Shell\CommandFactory::createBoxed()
```
### Backtrace:
```
#0 /../w/extensions/Diagrams/includes/Diagrams.php(113): MediaWiki\Extension\Diagrams\Diagrams->runCommand()
#1 /../w/extensions/Diagrams/includes/Hooks.php(54): MediaWiki\Extension\Diagrams\Diagrams->renderLocally()
#2 /../w/includes/parser/Parser.php(3921): MediaWiki\Extension\Diagrams\Hooks::MediaWiki\Extension\Diagrams\{closure}()
#3 /../w/includes/parser/PPFrame_Hash.php(340): Parser->extensionSubstitution()
#4 /../w/includes/parser/Parser.php(2886): PPFrame_Hash->expand()
#5 /../w/includes/parser/Parser.php(1557): Parser->replaceVariables()
#6 /../w/includes/parser/Parser.php(652): Parser->internalParse()
#7 /../w/includes/content/WikitextContent.php(374): Parser->parse()
#8 /../w/includes/content/AbstractContent.php(590): WikitextContent->fillParserOutput()
#9 /../w/includes/Revision/RenderedRevision.php(263): AbstractContent->getParserOutput()
#10 /../w/includes/Revision/RenderedRevision.php(235): MediaWiki\Revision\RenderedRevision->getSlotParserOutputUncached()
#11 /../w/includes/Revision/RevisionRenderer.php(215): MediaWiki\Revision\RenderedRevision->getSlotParserOutput()
#12 /../w/includes/Revision/RevisionRenderer.php(152): MediaWiki\Revision\RevisionRenderer->combineSlotOutput()
#13 [internal function]: MediaWiki\Revision\RevisionRenderer->MediaWiki\Revision\{closure}()
#14 /../w/includes/Revision/RenderedRevision.php(197): call_user_func()
#15 /../w/includes/poolcounter/PoolWorkArticleView.php(216): MediaWiki\Revision\RenderedRevision->getRevisionParserOutput()
#16 /../w/includes/poolcounter/PoolCounterWork.php(162): PoolWorkArticleView->doWork()
#17 /../w/includes/page/WikiPage.php(1281): PoolCounterWork->execute()
#18 /../w/includes/page/Article.php(2299): WikiPage->getParserOutput()
#19 /../w/extensions/MyVariables/src/Hooks/DisableCache.php(19): Article->getParserOutput()
#20 /../w/includes/HookContainer/HookContainer.php(155): MediaWiki\Extension\MyVariables\Hooks\DisableCache->onArticleViewHeader()
#21 /../w/includes/HookContainer/HookRunner.php(886): MediaWiki\HookContainer\HookContainer->run()
#22 /../w/includes/page/Article.php(719): MediaWiki\HookContainer\HookRunner->onArticleViewHeader()
#23 /../w/includes/actions/ViewAction.php(80): Article->view()
#24 /../w/includes/MediaWiki.php(531): ViewAction->show()
#25 /../w/includes/MediaWiki.php(313): MediaWiki->performAction()
#26 /../w/includes/MediaWiki.php(947): MediaWiki->performRequest()
#27 /../w/includes/MediaWiki.php(547): MediaWiki->main()
#28 /../w/index.php(53): MediaWiki->run()
#29 /../w/index.php(46): wfIndexMain()
#30 {main}
```

**Comment by kghbln** [comment]
@samwilson A fix appears to be available in the fork of this extension. Will be cool to get the fix into this repo. I will now switch to the fork for now.

**Comment by kghbln** [comment]
I can confirm that the fork works in the environment I mentioned.

**Comment by samwilson** [comment]
Thanks! Fixed, and released in 0.13.2.

**Comment by samwilson** [comment]
I also [added ](https://gerrit.wikimedia.org/r/c/mediawiki/core/+/1027458) `@since` to that method, to make things clearer.

**Comment by kghbln** [comment]
@samwilson Thanks a ton! Switched back and it works fine for me!
